### ISSUE TITLE
Question: is the ledger up-to-date?

### ISSUE THREAD

**Issue by chadjemmett** [prestia/scarcitybot#1]
I'm using your script to write my own simple one. Just for fun.
And when using this hash and date `cd8ab6ab905103b5e3c2b68da30732e4 03082021`
I use `c` as the digest and the date provided `03082021`
And that hash matches the next hash in the ledger: `93c08fdb6ed5b970ec989a2c957f0e4d`

Is there a 'date moved' missing to get the most recent hash of `1f59a889357aeda1c6fe1a32d90d22cc`
Thanks for your time. 
This is a cool project. I'm having fun learning the code workings.

**Comment by prestia** [comment]
I just updated the ledger with the latest version from the server. I don't plan on updating the repository whenever Scarcity moves, but hopefully having this latest version will help with the learning!
